# Generated by Django 2.0 on 2018-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professor_statistics',
            fields=[
                ('professor_name', models.CharField(max_length=140, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('overall_quality', models.FloatField()),
                ('would_take_again', models.PositiveSmallIntegerField()),
                ('level_of_difficulty', models.FloatField()),
                ('hotness', models.CharField(max_length=20)),
            ],
        ),
    ]
