# Generated by Django 2.0 on 2018-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='professor_statistics',
            new_name='Professors',
        ),
    ]
